/*
 * backend
 *
 * Todoapp backend: manage tasks
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: womeier@posteo.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Task {
    #[serde(rename = "done")]
    pub done: bool,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "title")]
    pub title: String,
}

impl Task {
    pub fn new(done: bool, id: i32, label: String, title: String) -> Task {
        Task {
            done,
            id,
            label,
            title,
        }
    }
}
