/*
 * backend
 *
 * Todoapp backend: manage tasks
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: womeier@posteo.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateTask {
    #[serde(
        rename = "done",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub done: Option<Option<bool>>,
    #[serde(
        rename = "label",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub label: Option<Option<String>>,
}

impl UpdateTask {
    pub fn new() -> UpdateTask {
        UpdateTask {
            done: None,
            label: None,
        }
    }
}
